spring:
  application:
    name: User-service

#configuration for h2 or mysql
#  h2:
#    console:
#      enabled: true
#
#  datasource:
#    url: jdbc:h2:mem:temp
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create

#  http://localhost:5050/browser/ pg admin uri
#configuration for postgres
#  datasource:
#    url: jdbc:postgresql://localhost:5432/userdb
#    username: root
#    password: root
#
#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

#configuration for mongodb
  data:
   mongodb:
     uri: mongodb://localhost:27017/userdb  # mongodb compass not cloud
#     uri: mongodb+srv://boroleujval4:pU9qMF5rNcKh3ZI0@ecom.vlo5qmn.mongodb.net/?retryWrites=true&w=majority&appName=ecom  #for cloud
     database: userdb
server:
  port: 8082

