spring:
  application:
    name: Product-service

#  h2:
#    console:
#      enabled: true
#
#  datasource:
#    url: jdbc:h2:mem:temp
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create

  datasource:
#    url: jdbc:postgresql://localhost:5432/product
    url: jdbc:postgresql://ep-royal-poetry-abgddkkd-pooler.eu-west-2.aws.neon.tech/product?sslmode=require
    username: product_owner
    password: npg_lSOij6PmMA9q

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

